import json
import io
import base64
from langchain_core.messages import SystemMessage, HumanMessage

from app.llm.groq_client import get_llm

SYSTEM_PROMPT = """
You are an AI Pharmaceutical Marketing Materials advisor.

Your job is to recommend the most relevant marketing materials for a sales rep to use with a specific HCP, based on their specialty, discussion topics, and past interactions.

Return ONLY JSON with these fields:
- recommended_materials: Array of 2-4 material names/descriptions (e.g., "Clinical trial brochure - Phase III", "Product X dosing card", "Patient education pamphlet - Condition Y")
- priority_material: The single most impactful material to bring next time
- rationale: 1-2 sentences explaining why these materials are recommended
- talking_points: Array of 2-3 key talking points to use with these materials
- brochure_content: 3-5 paragraphs of detailed brochure text that can be used as a leave-behind document for the HCP. Include product benefits, clinical data highlights, dosing info, and safety information. Make it professional and ready-to-print.

Rules:
1. Match materials to the HCP's specialty and the products discussed.
2. If the HCP raised objections, suggest materials that address those objections.
3. Always suggest at least 1 digital + 1 printed material.
4. Be specific - name actual types of pharma sales materials.
5. Never invent product names that aren't mentioned in the context.
"""


def _generate_brochure_pdf(recommendations: dict) -> str:
    """Generate a simple PDF brochure from recommendations and return as base64 string."""
    try:
        from fpdf import FPDF
    except ImportError:
        # fpdf2 not installed — return a plain text fallback encoded as base64
        text_lines = []
        text_lines.append("=" * 60)
        text_lines.append("PHARMACEUTICAL MATERIALS BROCHURE")
        text_lines.append("=" * 60)
        text_lines.append("")
        text_lines.append(f"Priority Material: {recommendations.get('priority_material', 'N/A')}")
        text_lines.append(f"Rationale: {recommendations.get('rationale', 'N/A')}")
        text_lines.append("")
        text_lines.append("Recommended Materials:")
        for i, mat in enumerate(recommendations.get('recommended_materials', []), 1):
            text_lines.append(f"  {i}. {mat}")
        text_lines.append("")
        text_lines.append("Talking Points:")
        for i, tp in enumerate(recommendations.get('talking_points', []), 1):
            text_lines.append(f"  {i}. {tp}")
        text_lines.append("")
        text_lines.append("Detailed Brochure Content:")
        text_lines.append("-" * 40)
        brochure = recommendations.get('brochure_content', 'No brochure content generated.')
        text_lines.append(brochure)
        text_lines.append("")
        text_lines.append("=" * 60)

        text_content = "\n".join(text_lines)
        return base64.b64encode(text_content.encode("utf-8")).decode("utf-8")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "Pharmaceutical Materials Brochure", ln=True, align="C")
    pdf.ln(6)

    # Priority Material
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Priority Material:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin, 6, recommendations.get("priority_material", "N/A"))
    pdf.ln(4)

    # Rationale
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Rationale:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin, 6, recommendations.get("rationale", "N/A"))
    pdf.ln(6)

    # Recommended Materials
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Recommended Materials:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i, mat in enumerate(recommendations.get("recommended_materials", []), 1):
        pdf.cell(0, 6, f"  {i}. {mat}", ln=True)
    pdf.ln(6)

    # Talking Points
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Key Talking Points:", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_x(pdf.l_margin + 10)
    for i, tp in enumerate(recommendations.get("talking_points", []), 1):
        pdf.cell(0, 6, f"{i}. {tp}", ln=True)
        pdf.set_x(pdf.l_margin + 10)
    pdf.ln(6)

    # Brochure Content
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Detailed Brochure:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(pdf.l_margin)
    brochure_text = recommendations.get("brochure_content", "No brochure content generated.")
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin, 6, brochure_text)
    pdf.ln(8)

    # Footer
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, "Generated by HCP CRM AI Assistant -- For internal use only", align="C")

    # Output to bytes
    pdf_bytes = pdf.output()
    return base64.b64encode(pdf_bytes).decode("utf-8")


def recommend_materials(interaction_data: dict) -> dict:
    """Generate material recommendations based on interaction context."""
    llm = get_llm()
    context = json.dumps(interaction_data, default=str)

    response = llm.invoke([
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=f"Interaction context:\n{context}")
    ])

    try:
        content = response.content.strip()
        # Strip markdown code fences if present
        if content.startswith("```"):
            lines = content.split("\n")
            content = "\n".join(lines[1:-1] if lines[-1].startswith("```") else lines[1:])
        # Strip double braces the LLM sometimes wraps in
        if content.startswith("{{") and content.endswith("}}"):
            content = content[1:-1]
        return json.loads(content)
    except Exception:
        return {
            "recommended_materials": [
                "Product information brochure",
                "Clinical reprints for relevant studies",
            ],
            "priority_material": "Product information brochure",
            "rationale": "General materials recommended for follow-up engagement.",
            "talking_points": [
                "Share key efficacy data",
                "Discuss real-world evidence",
            ],
            "brochure_content": "Please refer to the product information brochure for detailed clinical data, efficacy results, and safety information. This material is intended for healthcare professionals only.",
        }


def material_node(state):
    """LangGraph node: recommend marketing materials based on interaction."""
    extracted_data = state.get("extracted_data", {})
    user_input = state.get("user_input", "")

    # Use extracted data if available, otherwise pass the raw input
    context = extracted_data if extracted_data else {"user_query": user_input}

    recommendations = recommend_materials(context)

    # Generate PDF brochure as base64
    pdf_base64 = _generate_brochure_pdf(recommendations)

    state["tool_result"] = {
        "message": "Material recommendations generated. A brochure PDF is ready for download.",
        "recommendations": recommendations,
        "brochure_pdf": pdf_base64,
        "brochure_filename": "hcp_materials_brochure.pdf",
        "requires_download": True,
    }
    return state
